version: '3.8'

services:
  postgres:
    image: 'postgres:latest'
    environment:
      - POSTGRES_DB=${POSTGRES_DB}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_USER=${POSTGRES_USER}
    ports:
      - '5432:5432'

 # app:
 #   build: .
 #   depends_on:
  #    - postgres
   # environment:
     # DB_URL: ${DB_URL}
     # DB_USER: ${DB_USER}
     # DB_PASSWORD: ${DB_PASSWORD}
   # ports:
   #   - '8080:8080'
  #  networks:
   #   - my-network

networks:
  my-network:
